### ISSUE TITLE
Year format not working correctly

### ISSUE THREAD

**Issue by ghost** [pryley/alfred-the-archive#1]
When creating a note year appears as 2006, not 2020! e.g. 200620105319

**Comment by pryley** [comment]
I had previously set the format on my machine to a two digit year and ending with the two digit second and forgot that when I change the values, it changes the default values when I publish the workflow. 

Please download the latest release which fixes this. You can also type `arconfig` in Alfred and customise the datetime format yourself. 

The latest release also generates unique Zettel IDs (so using seconds are no longer needed). Instead, the workflow increments the datetime minute used for the UID if one already exists.

**Comment by pryley** [comment]
I had set the format on my machine to a two digit year and ending with the two digit second and forgot that when I change the values, it changes the default values to those when I publish the workflow. However, the latest release now also generates unique Zettel IDs so the seconds are not longer needed.

**Comment by ghost** [comment]
Hey Paul
Thanks for replying, it’s now working brilliantly. This is a great piece of work.
Regards

--
Derek Reid-Crawford
derek@z817.uk
