### ISSUE TITLE
`ar searchterm` displays bad results if file name contains "."

### ISSUE THREAD

**Issue by wduquette** [pryley/alfred-the-archive#2]
I have a note called "202007171712 Mr. Charleston" (a character in a book I wrote).  If I use the "ar" workflow and type "ar Charleston", the note pops up as the first result (I have Search Content set to true, BTW).  But the title of the note displayed in the list is "202007171712 Mr".

(Thanks for putting this workflow together, BTW.)

**Comment by wduquette** [comment]
There's a simple workaround: Set "Prefer Filename to Title" to false.

**Comment by pryley** [comment]
Fixed in v1.7.0
