### ISSUE TITLE
arnew doesn't pick up "Use ID for empty file names" in The Archive 1.5.5

### ISSUE THREAD

**Issue by wduquette** [pryley/alfred-the-archive#3]
According to the README, the "arnew" command is supposed to use the Command modifier to remove the zettel ID from the file name if the "Use ID for empty file names" preference is set in The Archive.  From what I can tell, though, the relevant script can tell whether that flag is set or not.  Maybe the preference format changed?

I always want to include the Zettel ID, so I went in and edited the relevant script so that it's always set to "Remove"; now it works fine for me.  But I thought you should know. :-)

**Comment by pryley** [comment]
This is working for me.

Here is the option in The Archive preferences:
![image](https://user-images.githubusercontent.com/134939/88138659-bbe2aa00-cbb3-11ea-9e85-cf1bfaec8ab2.png)

This is `arnew` with no modifier key pressed:
![image](https://user-images.githubusercontent.com/134939/88138566-8fc72900-cbb3-11ea-8e8a-abd2754d56c2.png)

This is `arnew` with the ⌘ modifier key pressed:
![image](https://user-images.githubusercontent.com/134939/88138578-948bdd00-cbb3-11ea-963d-34aa80456daf.png)

The result each time is as expected.

**Comment by pryley** [comment]
Ah, the problem was that The Archive does not set this option in the application pref file unless it is changed in preferences, and the Workflow was setting the wrong default when this was the case.

Fixed in v1.7.1
