### ISSUE TITLE
Python 2 no longer available in macOS 12.3

### ISSUE THREAD

**Issue by ddeboer** [pryley/alfred-the-archive#5]
The recent macOS 12.3 update removed Python 2, which this workflows depends on. Would it be possible to use Python 3 instead? See also https://www.alfredforum.com/topic/17941-making-python-2-workflows-work-on-macos-monterey-123-and-above/.

**Comment by romanthekat** [comment]
Unluckily simply `2to3` for the code is not enough, `Plist.py` now fails with `ModuleNotFoundError: No module named 'Foundation'`.

Possibly migrating on https://docs.python.org/dev/library/plistlib.html would help, but using external libraries within the plugin can be a tricky thing

**Comment by pryley** [comment]
@ddeboer @romanthekat Please try the v2.0.0-beta1 pre-release and let me know if everything works correctly.

**Comment by romanthekat** [comment]
@pryley looks good, thank you ^_^

**Comment by ddeboer** [comment]
The new release works well for me on macOS 12.3. Thank you so much @pryley! Really enjoying this workflow, which I use daily.
