### ISSUE TITLE
When entering title value after 'arnew' keyword, Alfred interprets as Google search

### ISSUE THREAD

**Issue by dskesler** [pryley/alfred-the-archive#6]
When I begin to type `arnew` keyword in Alfred query, I correctly see the option to create a new Archive note:
![scrx 2022-04-15-11-24 Alfred Preferences 3](https://user-images.githubusercontent.com/24609864/163595978-06e18bb3-608f-46d0-9bb1-8d1fddd37512.png)

But when I begin to type in the title of the new note `arnew some new note`, Alfred interprets the query string as a Google search:
![scrx 2022-04-15-11-24 Alfred Preferences 2](https://user-images.githubusercontent.com/24609864/163595976-bd944fcd-0bc7-4ea3-a010-b4ed3574e998.png)

I have re-installed the alfred-the-archive workflow, but that did not fix the issue. Any suggestions for a fix?
Thanks.

**Comment by pryley** [comment]
Are you using the v2.0.0 beta?

**Comment by dskesler** [comment]
Ah, I was not. I had not seen a link to the beta. 

After installing the beta, it fixed the issue.

Thanks. Very helpful workflow. I will be donating.
