### ISSUE TITLE
"Cannot fetch the URL"

### ISSUE THREAD

**Issue by nicksergeant** [pryley/alfred-the-archive#8]
I'm running into the error "Cannot fetch the URL":

<img width="429" alt="image" src="https://user-images.githubusercontent.com/27332/211045639-e6859815-19f5-49c7-896d-c4093573b6d3.png">

When running `arurl https://nicksergeant.com/transitioning-to-a-rest-api-in-support-of-a-modern-front-end/`

I've successfully installed pandoc:

```
❯ brew install pandoc
Running `brew update --auto-update`...
==> Fetching pandoc
==> Downloading https://ghcr.io/v2/homebrew/core/pandoc/manifests/2.19.2
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/pandoc/blobs/sha256:62c83be98424758ef00e8536944ec94a0b8d824fddccc11c257020e3ead5a0c0
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:62c83be98424758ef00e8536944ec94a0b8d824fddccc11c257020e3
######################################################################## 100.0%
==> Pouring pandoc--2.19.2.arm64_monterey.bottle.tar.gz
🍺  /opt/homebrew/Cellar/pandoc/2.19.2: 10 files, 251.2MB
==> Running `brew cleanup pandoc`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).

❯ pandoc -h
pandoc [OPTIONS] [FILES]
  -f FORMAT, -r FORMAT  --from=FORMAT, --read=FORMAT
  ...
```

I don't see anything else that might need to be installed in https://github.com/pryley/alfred-the-archive/blob/master/fetch_url.py, but perhaps I'm missing a dep?

**Comment by pryley** [comment]
No, but [cc468d8](https://github.com/pryley/alfred-the-archive/commit/cc468d8b5b91275c5dbc08a77333bbc8b1a1e02e) should fix the problem.

**Comment by nicksergeant** [comment]
@pryley thanks!
